spring.application.name=TwitchMiner
server.port=8083
logging.level.aiss_L3.controller=DEBUG

twitch.base-url=https://api.twitch.tv/helix
twitch.client-id=${TWITCH_CLIENT_ID}
twitch.token=${TWITCH_TOKEN}
twitch.default-query=Twitch
